name: EC2 System Info

on:
  workflow_dispatch:

jobs:
  system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Check System Info
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== System Information ==="
            uname -a
            echo -e "\n=== Distribution Info ==="
            lsb_release -a
            echo -e "\n=== CPU Info ==="
            cat /proc/cpuinfo | grep "model name" | head -n1
